### ISSUE TITLE
Config Peds is only set for 1 location

### ISSUE THREAD

**Issue by DistrictZion** [vinceyyyy/esx_GlassHeroes#1]
As the title says, config.Peds is actually set in the client, or the whole code for only 1 location. Multiple locations do not work.

**Comment by vinceyyyy** [comment]
I just noticed it's a bit misleading that I named it Config.Ped(**s**). In this script, there is only supposed to be 1 NPC, hence the name "GlassHeroes", as there is only one of these mechanic shops in Los Santos. Unfortunately, with the way I coded it, it will be really hard to implement adding multiple NPCs, but I will take a look at it.

**Comment by Yoshi-Developments** [comment]
2nd this. Would love to have the ability to spawn in multiple at other mechanics accross the map to help with the load on players and to perform repairs when the shop is closed.

**Comment by vinceyyyy** [comment]
Hey, I actually did make it possible to spawn multiple NPCs, just add them to the Config.Peds. Let me know if you encounter any issues, but it should work.
